# #Ordway
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.4.39
#

$LOAD_PATH.push File.expand_path("lib", __dir__)
require "ordway-sdk/version"

Gem::Specification.new do |s|
  s.name        = "ordway-sdk"
  s.version     = Ordway::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Pro Trainings"]
  s.email       = [""]
  s.homepage    = "https://github.com/ProTrainings/ordway-sdk"
  s.summary     = "Ordway Ruby Gem"
  s.description = "Ruby SDK for connecting to Ordway API"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 3.3.0"

  s.add_runtime_dependency "addressable", "~> 2.3", ">= 2.3.0"
  s.add_runtime_dependency "faraday", "~> 2.9"
  s.add_runtime_dependency "faraday-retry", "~> 1.0"
  s.add_runtime_dependency "json", "~> 2.1", ">= 2.1.0"

  s.files         = `find *`.split("\n").uniq.sort.reject(&:empty?)
  s.executables   = []
  s.require_paths = ["lib"]
  s.metadata["rubygems_mfa_required"] = "true"
end
