# frozen_string_literal: true

# #Ordway
#
# Ruby SDK for connecting to the Ordway API
#
# OpenAPI spec version: 1.0.0
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
# Swagger Codegen version: 2.4.39

$LOAD_PATH.push File.expand_path("lib", __dir__)
require "ordway-sdk/version"

Gem::Specification.new do |s|
  s.name        = "ordway-sdk"
  s.version     = Ordway::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Pro Trainings"]
  s.email       = [""]
  s.homepage    = "https://github.com/ProTrainings/ordway-sdk"
  s.summary     = "Ruby SDK for Ordway API"
  s.description = "A Ruby SDK for interacting with the Ordway API, providing a simple and intuitive interface for billing and subscription management."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7.0"

  # Dependencies
  s.add_dependency "addressable", "~> 2.8"
  s.add_dependency "faraday", "~> 2.7"
  s.add_dependency "faraday-retry", "~> 2.2"
  s.add_dependency "json", "~> 2.6"

  # Development dependencies
  s.add_development_dependency "rspec", "~> 3.12"
  s.add_development_dependency "webmock", "~> 3.19"
  s.add_development_dependency "rubocop", "~> 1.57"
  s.add_development_dependency "rubocop-rails", "~> 2.24"
  s.add_development_dependency "rubocop-rspec", "~> 3.5"

  # Files
  s.files         = `find *`.split("\n").uniq.sort.reject(&:empty?)
  s.executables   = []
  s.require_paths = ["lib"]

  # Metadata
  s.metadata = {
    "rubygems_mfa_required" => "true",
    "homepage_uri" => s.homepage,
    "source_code_uri" => s.homepage,
    "changelog_uri" => "#{s.homepage}/blob/main/CHANGELOG.md",
    "documentation_uri" => "https://www.rubydoc.info/gems/#{s.name}/#{s.version}",
    "bug_tracker_uri" => "#{s.homepage}/issues"
  }
end
