=begin
#Ordway

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for Ordway::CustomersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomersApi' do
  before do
    # run before each test
    @instance = Ordway::CustomersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersApi' do
    it 'should create an instance of CustomersApi' do
      expect(@instance).to be_instance_of(Ordway::CustomersApi)
    end
  end

  # unit tests for delete_customers
  # Delete Customer
  # This call is used to delete a specific Customer.   Caution is recommended when deleting a Customer as revenue and reporting are both affected.
  # @param id The unique id of the customer.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customers
  # Get Customer
  # This call is used to retrieve a specific Customer.
  # @param id The unique id of the customer.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20023]
  describe 'get_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customers_verbose
  # Get All Customer Information
  # NOTE: Support for this API will be discontinued in October 2022. Please use GET Customer, GET Subscriptions, or Get Invoices APIs as alternatives for additional business objects. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20025]
  describe 'get_customers_verbose test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_customers
  # List Customers
  # A Customer Account is the record of a business or individual purchasing goods or services from your business. Customer Accounts contains key metrics and all relevant customer settings including contact, billing and payment terms, and other pertinent details specific to each customer.   This call is used to retrieve all Customers.   Refer to the following article for additional information: [Customer Basics](https://support.ordwaylabs.com/hc/en-us/articles/360053191051-Customer-Basics).  
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :size The size of the result set. Default is 20 and max is 50.
  # @option opts [Float] :page This parameter will help page through large result sets. Default is 1.
  # @option opts [String] :sort List the fields to sort the result set. Example GET /customers?sort&#x3D;name,status%20desc
  # @return [InlineResponse20021]
  describe 'list_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_bulk_disable_customer_portal
  # Bulk Disable Customer Portal
  # This call disables portal access for multiple Customers at one time. Portal access for all active contacts associated with the Customer will be disabled. The process will occur asynchronously to the API request.  Precondition:   This API can be used only if the Customer Portal feature is enabled.
  # @param x_user_email 
  # @param x_user_token 
  # @param x_user_company 
  # @param x_api_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Body12] :body 
  # @return [InlineResponse20016]
  describe 'post_bulk_disable_customer_portal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_bulk_invite_to_portal
  # Bulk Invite to Customer Portal
  # This call allows multiple Customers to be invited to the portal at one time. Only billing contacts of the Customers will be invited. The process will occur asynchronously to the API request.  Precondition:   This API can be used only if the Customer Portal feature is enabled.
  # @param [Hash] opts the optional parameters
  # @option opts [Body11] :body 
  # @return [InlineResponse20016]
  describe 'post_bulk_invite_to_portal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_customers
  # Create Customer
  # This call is used to create a new Customer.  
  # @param [Hash] opts the optional parameters
  # @option opts [Customers] :body 
  # @return [InlineResponse20022]
  describe 'post_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_disable_customer_portal
  # Disable Customer Portal
  # This call is used for disabling all the portal user&#39;s (contacts) access to the Customer Billing Portal application. Disabling will only work on the contacts whose portal status is in Enabled state.  Precondition:  This API can be used only if the Customer Portal feature is enabled.
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20027]
  describe 'post_disable_customer_portal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_invite_to_customer_portal
  # Invite to Customer Portal
  # This call can be used to: 1. Invite Customers Bill Contact with a valid email address to the Customer Billing Portal. When an invitation is successful, the Contact will receive a Portal Registration email. This will change the portal status of the contact from empty/nil to Pending status. 2. Re-send a portal invitation to contacts with Pending or Expired portal status. 3. Re-enable portal access to a portal user with Disabled status. Once the request is successful, the contact portal status will change from Disabled to Enabled status.  Precondition:   This API can be used only if the Customer Portal feature is enabled. If the contact portal status is already Enabled, API will return an error.   Refer to the Help Center for additional information on this topic. 
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_user_email 
  # @option opts [String] :x_user_token 
  # @option opts [String] :x_user_company 
  # @option opts [String] :x_api_key 
  # @return [InlineResponse20026]
  describe 'post_invite_to_customer_portal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_customers
  # Update Customer
  # This call is used to update an existing Customer.
  # @param id The unique id of the customer.
  # @param [Hash] opts the optional parameters
  # @option opts [Customers] :body 
  # @return [InlineResponse20024]
  describe 'put_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
